language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"

script: "npm run coverage"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

